"""VLM judge utilities for SelTDA reward experiments."""

from judge.data import (
    AnswerPools,
    GENERIC_MEDICAL_ANSWERS,
    ImagePoolItem,
    JudgeCandidate,
    JudgePair,
    NegativeSampler,
    YES_NO,
    answer_text,
    build_answer_pools,
    build_judge_pairs,
    infer_answer_type,
    load_image_pool,
    load_records,
    question_prefix,
)
from judge.prometheus import (
    DEFAULT_RUBRIC,
    NO_REFERENCE_TEXT,
    PrometheusResult,
    PrometheusScorer,
    PrometheusVisionScorer,
    StaticPrometheusScorer,
    _feedback_from_raw,
    build_prometheus_prompt,
    parse_prometheus_score,
    score_to_reward,
)
from judge.factory import (
    ResolvedPrometheusConfig,
    build_prometheus_scorer,
    resolve_prometheus_config,
    write_judge_snapshot,
)
from judge.reward import (
    apply_reward_penalties,
    batch_diagnostics,
    compute_pairwise_metrics,
    duplicate_question_penalties,
    generic_answer_penalty,
    group_normalized_advantages,
    length_penalty,
    score_distribution,
)

__all__ = [
    "AnswerPools",
    "DEFAULT_RUBRIC",
    "GENERIC_MEDICAL_ANSWERS",
    "ImagePoolItem",
    "JudgeCandidate",
    "JudgePair",
    "NegativeSampler",
    "NO_REFERENCE_TEXT",
    "PrometheusResult",
    "PrometheusScorer",
    "PrometheusVisionScorer",
    "ResolvedPrometheusConfig",
    "StaticPrometheusScorer",
    "YES_NO",
    "_feedback_from_raw",
    "apply_reward_penalties",
    "answer_text",
    "batch_diagnostics",
    "build_answer_pools",
    "build_judge_pairs",
    "build_prometheus_scorer",
    "build_prometheus_prompt",
    "compute_pairwise_metrics",
    "duplicate_question_penalties",
    "generic_answer_penalty",
    "group_normalized_advantages",
    "infer_answer_type",
    "length_penalty",
    "load_image_pool",
    "load_records",
    "parse_prometheus_score",
    "question_prefix",
    "resolve_prometheus_config",
    "score_distribution",
    "score_to_reward",
    "write_judge_snapshot",
]
