defaults:
  - filter_pseudo

gates:
  conf:
    enabled: false
  itm:
    enabled: false
  vqascore:
    enabled: true
    keep_top: 0.75
    model: clip-flant5-xl
    batch_size: 8
  xcons:
    enabled: false

stratify:
  enabled: false

coreset:
  enabled: false
