image_folder: datasets/pathvqa/images
output_folder: outputs/generated_qa/pathvqa_grpo_teacher_200x8
annotations: outputs/generated_qa/pathvqa_grpo_teacher_200x8/pathvqa_train_unique_images.json
pretrained: outputs/grpo_teacher/pathvqa_prometheus_base7b/checkpoint_final.pth
output_annotations_name: generated_qa.json
image_size: 384
max_length: 30
min_length: 5
num_beams: 3
prompt: ''
torch_home: null
vit: base
questions_per_image: 2
multimodal_encoder_decoder_config: configs/med_config.json
batch_size: 32
truncate_to: null
num_workers: 4
top_p: 0.9
vqa_dataset_origin: 'vqa'
dry_run: false
shuffle: false
parse_rationale: false
