image_folder: /home/phongnguyen/SelTDA/datasets/coco2017/unlabeled2017
output_folder: /home/phongnguyen/SelTDA/datasets/aokvqa
annotations: null
pretrained: /home/phongnguyen/SelTDA/orchestration/state/teacher_1.pth
output_annotations_name: synthetic_data_rl_raw.json
image_size: 384
max_length: 40
min_length: 5
num_beams: 3
prompt: "Question:"
torch_home: /home/phongnguyen/SelTDA/cache/torch_home
vit: base
questions_per_image: 2
multimodal_encoder_decoder_config: /home/phongnguyen/SelTDA/configs/med_config.json
batch_size: 16
truncate_to: 17000
num_workers: 4
top_p: 0.9
vqa_dataset_origin: vqa
dry_run: false
shuffle: true
parse_rationale: false
